aws_region           = "ap-south-1"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidr   = "10.0.1.0/24"
availability_zone    = "ap-south-1a"
ami_id               = ""  #  custom AMI id built with packer and ansible.
instance_type        = "t2.micro"
key_name             = "iac-demo-assignment"
project              = "iac-nginx"
environment          = "dev"
