- name: Install NGINX with shell
  shell: |
    amazon-linux-extras enable nginx1
    yum clean metadata
    yum install -y nginx
  args:
    executable: /bin/bash

- name: Start and enable NGINX
  raw: systemctl enable nginx && systemctl start nginx


- name: Copy index page
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: '0644'

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Ensure /etc/ssl/private and /etc/ssl/certs directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/ssl/private
    - /etc/ssl/certs


- name: Generate self-signed SSL cert
  shell: |
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/CN=localhost"
  args:
    creates: /etc/ssl/certs/nginx-selfsigned.crt

- name: Set secure permissions on private key
  file:
    path: /etc/ssl/private/nginx-selfsigned.key
    mode: "0600"
