- name: Configure NGINX with HTTPS on EC2
  hosts: all
  become: yes

  tasks:
    - name: Create simple index.html
      copy:
        content: "<h1>Hello from NGINX with SSL on Amazon Linux 2 (via Packer + Ansible)</h1>"
        dest: /usr/share/nginx/html/index.html

    - name: Deploy NGINX SSL config
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              sendfile on;
              keepalive_timeout 65;

              server {
                  listen 443 ssl default_server;
                  server_name _;

                  ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
                  ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

                  ssl_protocols TLSv1.2 TLSv1.3;
                  ssl_ciphers HIGH:!aNULL:!MD5;

                  location / {
                      root /usr/share/nginx/html;
                      index index.html index.htm;
                  }
              }

              server {
                  listen 80;
                  server_name _;
                  return 301 https://$host$request_uri;
              }
          }

    - name: Restart NGINX to apply config
      command: systemctl restart nginx
